### ISSUE TITLE
Create mature designs to focus first build on

### ISSUE THREAD

**Issue by andrewbarnesweb** [somedevsdo/blog#15]
We need some mature page designs with design specs to develop against.

In the first instance, this means a:

- Home page (list of blog posts)
- Post (a blog page)
- Author (an authors bio and links to latest articles)

**Comment by andrewbarnesweb** [comment]
The current designs are being worked on here: https://www.figma.com/file/Oc9v5LR4SPwwaQyijhEXnR/blog?node-id=0%3A2

Link should be viewable to all. Give me a shout if you need editing permissions.

**Comment by andrewbarnesweb** [comment]
Needs some work, but trying to get the concept across that the initial site can just be purely made up blog posts, to get us launched more quickly. So the homepage would just be a feed basically. And the hero area just pre populated with frontmatter from the latest post.

![image](https://user-images.githubusercontent.com/20924669/119253046-3058f180-bba7-11eb-8e0b-e4c4e41a4f31.png)

**Comment by andrewbarnesweb** [comment]
Just looking through stuff. Noticed we have uppercase headers in places. This should generally be avoided for readability. Fine for things like labels and buttons.

**Comment by markgaze** [comment]
> Just looking through stuff. Noticed we have uppercase headers in places. This should generally be avoided for readability. Fine for things like labels and buttons.

Sack the Designer... 😛

**Comment by andrewbarnesweb** [comment]
Closing as done.

- Design file: https://www.figma.com/file/Oc9v5LR4SPwwaQyijhEXnR/Website?node-id=26%3A29
- Desktop prototype: https://www.figma.com/proto/Oc9v5LR4SPwwaQyijhEXnR/Website?node-id=245%3A714&scaling=min-zoom&page-id=26%3A29
