### ISSUE TITLE
Add Percy (😬)

### ISSUE THREAD

**Issue by andrewbarnesweb** [somedevsdo/blog#20]
Investigate adding Percy to the site. Whether it needs an org, and we all need new accounts etc.

**Comment by davidn0rman** [comment]
I... think this is blocked, until we get a central email account?

**Comment by markgaze** [comment]
> I... think this is blocked, until we get a central email account?

Don't think so, we used a Percy account with multiple members before so unless it's changed then we should be OK?

**Comment by andrewbarnesweb** [comment]
Agree. Think it was more about the org, and it couldn't be linked owned by one of our accounts with GitHub already linked. To stop people creating new orgs for every project. I'll have a look in a bit.

**Comment by davidn0rman** [comment]
Cool. Will leave it to you then. 🙂

**Comment by andrewbarnesweb** [comment]
I can't see any way to create a new organisation with my current account. Even though the docs suggest I can: https://docs.percy.io/docs/percy-platform-basics#what-you-should-know-about-organizations

**Comment by markgaze** [comment]
We have an account now, if we still think this is worthwhile!

**Comment by andrewbarnesweb** [comment]
Tests and Cypress is a bit hacky right now. I think to use Percy, we'd need to mock up a hell of a lot - including stuff like the MD posts? Although I think Percy allows you to define bits that change, just feel like it could be the whole page depending on which posts are loading/loaded.

I guess devil's advocate for now, is the site shouldn't grow too much - and if it does we can invest more time in it then?

**Comment by markgaze** [comment]
> Tests and Cypress is a bit hacky right now. I think to use Percy, we'd need to mock up a hell of a lot - including stuff like the MD posts? Although I think Percy allows you to define bits that change, just feel like it could be the whole page depending on which posts are loading/loaded.
> 
> I guess devil's advocate for now, is the site shouldn't grow too much - and if it does we can invest more time in it then? 

On the one site I've used it on which is similar to this, it just ended up wasting my time more than anything. It's definitely useful to make sure everything looks good but I agree, I'd maybe want a test page for all the Percy tests so that it was effectively just static and we were just testing the styling

**Comment by andrewbarnesweb** [comment]
Shall we close for now?

**Comment by markgaze** [comment]
> Shall we close for now?

Yeah, I think so!
