### ISSUE TITLE
Automate Lighthouse checks

### ISSUE THREAD

**Issue by andrewbarnesweb** [somedevsdo/blog#26]
Since we're building a full site, it'd be worthwhile running some full page checks to get any help with things like performance and SEO.

**Comment by markgaze** [comment]
Something to keep in mind, I did this on the Rams site and ended up only doing it on builds in the main branch because it takes so long to run and ends up slowing down merge times 🙂

**Comment by andrewbarnesweb** [comment]
I've only used it once, and gave up on it. See how we go, can always do some manual stuff to up our game.
