### ISSUE TITLE
Authors to get ability to have optional socials and links

### ISSUE THREAD

**Issue by andrewbarnesweb** [somedevsdo/blog#27]
Authors should be able to optionally add handles in frontmatter/JSON to be displayed on their page.

Initial suggestions:

- Twitter
- GitHub
- Instagram
- LinkedIn
- Polywork (😬)
- Dev.to / Medium
- Facebook?! ❌

**Comment by benmatselby** [comment]
I actually like the way Polywork does it. Seemingly allowing any URL with internal logic for the display icon.

**Comment by andrewbarnesweb** [comment]
Yeah, that's pretty cool! So you'd pump an array of URL's in, and it'd work out what icon to show.

**Comment by benmatselby** [comment]
The code that does this is done. We now need the designs for  #7 to complete this. Closing this item down, as the real work is in #7
