### ISSUE TITLE
A name...

### ISSUE THREAD

**Issue by davidn0rman** [somedevsdo/blog#29]
Probably best if we have an issue for this, so we can dump name ideas in as and when we come up with them.

**Comment by davidn0rman** [comment]
I guess... why couldn't this be barcode? Other than the URL being on 'offer'?

![image](https://user-images.githubusercontent.com/20046480/119497168-2b896e80-bd5c-11eb-9d31-74782369e762.png)

Bar code. Like sitting in Starbucks with your laptop, but not.

**Comment by benmatselby** [comment]
LikesittinginStarbuckswithyourlaptopbutnot.com is free, Dave

**Comment by davidn0rman** [comment]
Some shitbag has http://www.bar.codes/ too. Which would have been epic.

**Comment by andrewbarnesweb** [comment]
Most variations of `bar code` / `bar codes` / `bar coders` all gone.

I think two we found with Omega in, were `Omega Club` and `Omega Musings`. Although with regards to musings, pigeon holes us somewhat.

**Comment by markgaze** [comment]
`crapp-team-3`?

**Comment by andrewbarnesweb** [comment]
![image](https://user-images.githubusercontent.com/20924669/119508414-a4da8e80-bd67-11eb-82f1-e212044141cf.png)

**Comment by andrewbarnesweb** [comment]
You can never leave. Strict one in one out policy.

**Comment by benmatselby** [comment]
https://www.youtube.com/watch?v=HFZQt6kj2kM

**Comment by andrewbarnesweb** [comment]
![image](https://user-images.githubusercontent.com/20924669/119510485-76f64980-bd69-11eb-9693-d7de7b8604c7.png)

**Comment by benmatselby** [comment]
There is some branding to be had with “some devs do”

- Some devs do blogs
- Some devs do open source
- Some devs do fire side chats
- Some devs do CRM products
- Some devs do freelance …

**Comment by nina-rafieifar** [comment]
<img width="1101" alt="Screenshot 2021-05-25 at 15 51 01" src="https://user-images.githubusercontent.com/45998039/119519060-04896780-bd71-11eb-8e0a-1c3d37bcc083.png">

**Comment by andrewbarnesweb** [comment]
The bar code club is cool!

**Comment by davidn0rman** [comment]
And cheap!
