### ISSUE TITLE
Add featured image to posts

### ISSUE THREAD

**Issue by andrewbarnesweb** [somedevsdo/blog#32]
Add a link in the frontmatter to a featured image. And get it to show up at the top of the page.

![image](https://user-images.githubusercontent.com/20924669/119334476-1260bf00-bc83-11eb-8964-fefaccec6a66.png)

**Comment by andrewbarnesweb** [comment]
Anyone know the best place to store an image for a blog post? Would the posts be self contained folders with their images inside, or would they all live here somewhere? 
![image](https://user-images.githubusercontent.com/20924669/119334763-64a1e000-bc83-11eb-9f13-e2820539579d.png)

**Comment by benmatselby** [comment]
Good question, would need to do some digging. My personal site I have it sat in `public`. Pros: One place, easily re-use. Cons: manual search to find usage.

**Comment by markgaze** [comment]
I think all images have to be in the `public` folder to be included in the build in Next. Unless you're specifically `import`-ing them so we'd just need a folder structure that matches the posts structure?

**Comment by andrewbarnesweb** [comment]
Closed as done
