### ISSUE TITLE
Need someone amazing to go through and get rid of the ESLint warnings

### ISSUE THREAD

**Issue by andrewbarnesweb** [somedevsdo/blog#46]
- run `npm run lint`
- See warnings
- Clear them off

(they are also visible in GitHub)

![image](https://user-images.githubusercontent.com/20924669/119613305-c5045f00-bdf4-11eb-8159-036fa43445f2.png)

Might need some discussion on prop spreading and the `dangerouslySetInnerHTML`.

**Comment by andrewbarnesweb** [comment]
@markgaze I think we'd want it to error if we're not defining a return function?

**Comment by markgaze** [comment]
> @markgaze I think we'd want it to error if we're not defining a return type on functions?

Yeah, agreed! I just put it on as a warning to ease people in but I'm happy for it to be super strict in linting and TS 🙂
