### ISSUE TITLE
Logo added to site as SVG without exclusion zone

### ISSUE THREAD

**Issue by davidn0rman** [somedevsdo/blog#51]
Logo needs to be added to the site as an asset that can be used throughout. It should be SVG and have no exclusion zone, so that spacing can be managed on a case by case basis.

![image](https://user-images.githubusercontent.com/20046480/124108658-438c9600-da5e-11eb-9359-aec1b2e88b87.png)

Files attached.

**[Logos.zip](https://github.com/somedevsdo/blog/files/6747428/Logos.zip)**

---

_**Original issue below. See above for current issue.**_

Just a quick 15 min sketch of some brain fart ideas. Might get the creative juices going. Quite like the last one myself, or some variety of it...

Trying to get across...
- It's a blog
- It's by techies, namely devs
- But could be about anything web/dev

Could _just be a logo_. Meaning, it's agnostic, and paring it with our name makes it become associated  with us. Think nike and the tick, Audi and 4 rings, Mercedes and the star, etc.

![image](https://user-images.githubusercontent.com/20046480/119639588-a9f31880-be0f-11eb-8a3f-18b70c70fa18.png)

**Comment by andrewbarnesweb** [comment]
Love it. Want to steer away from it being a blog though. Plans to take over the world.

Hope you did this on your iPad.

**Comment by davidn0rman** [comment]
I either:
- Did, or
- Used traditional media, and my pencil got blunter as I went and scanned it in with a doc scanner app

Will let you decide.

>Want to steer away from it being a blog though.

But the main bulk of content will be write ups, tutorials, posts etc?

**Comment by benmatselby** [comment]
> But the main bulk of content will be write ups, tutorials, posts etc?

Until we get a contract or write our own product.

**Comment by andrewbarnesweb** [comment]
Yeah. Once the blog is up and running, we'll start adding more to the site. Like projects page etc. 

Highlighting some of the stuff we're proud of and have a delivered. Mark's in talks to get us involved on the depth chart app!

Potential goal, to make money. So that should be the end game in my opinion. So a generic logo would be preferred. 

(if we don't make money. I'm still happy learning stuff and delivering bits and bobs 👍🏻 )

**Comment by davidn0rman** [comment]
Thoughts?

## Dark
<img width="512" alt="Logo 4" src="https://user-images.githubusercontent.com/20046480/120121415-33ea0b00-c19b-11eb-8334-488c14a5543e.png">

## Light
<img width="512" alt="Logo 5" src="https://user-images.githubusercontent.com/20046480/120121418-377d9200-c19b-11eb-9a2b-a26676138c68.png">

## Light on an image
<img width="512" alt="Logo 6" src="https://user-images.githubusercontent.com/20046480/120121430-4cf2bc00-c19b-11eb-97b3-2033f5aad412.png">

## On a post
<img width="1192" alt="Light@2x" src="https://user-images.githubusercontent.com/20046480/120121448-70b60200-c19b-11eb-8c9d-b74eefc3ba6b.png">

## Playing with colours. (I like the last combo!)
![Frame 1](https://user-images.githubusercontent.com/20046480/120121510-ce4a4e80-c19b-11eb-830a-ae456511a446.png)

**Comment by davidn0rman** [comment]
OK. If we like this logo, I've come down to 2 coloured version. One being solid, one being a mix.

![Frame 1](https://user-images.githubusercontent.com/20046480/120231792-19229f80-c24a-11eb-9b8d-d5639c4693e8.png)

🚀 For one colour
🎉 For multicolour

(Bare in mine, we'd have mono versions too regardless, all black-ish and all white)

**Comment by andrewbarnesweb** [comment]
Done now: 
![image](https://user-images.githubusercontent.com/20924669/123750141-244f0680-d8ae-11eb-8496-331291c0974f.png)

@davidn0rman think we could do with a version with no exclusion zone that can be added to the site, so will refactor this issue.

**Comment by andrewbarnesweb** [comment]
Done ❤️
