### ISSUE TITLE
Define the social card

### ISSUE THREAD

**Issue by benmatselby** [somedevsdo/blog#54]
![image](https://user-images.githubusercontent.com/178634/119719605-e438d600-be60-11eb-9b73-bbadbfe57870.png)

We need to hook into the social meta data to get this to display correctly

**Comment by andrewbarnesweb** [comment]
What a great bit of functionality I've introduced! 

The GitHub one is super cool where it embeds the user's avatar (I think?)!

**Comment by benmatselby** [comment]
Closed in favour of #57
