### ISSUE TITLE
I think we should extract and create a package for SocialLink

### ISSUE THREAD

**Issue by benmatselby** [somedevsdo/blog#56]
The SocialLink component (which can be renamed if need be) could become it's own React package. Through in a URL, and it will figure out the icon to use. 

We should allow it to be flexible, so maybe allow class names to be thrown in etc.

This issue is to help gather thoughts and a plan before we execute this (if we actually do)

**Comment by benmatselby** [comment]
@andrewbarnesweb You want to pop your thoughts on here matey?

**Comment by andrewbarnesweb** [comment]
So as I see it as from your initial proposal would be a fairly basic component in a package ❤️  (great idea). So it'll be worth understanding some of the things we can do here to make it attractive past an initial version. 

Some cool things would be....

- Consumer send in the size. Can we just accept units? `2rem`, `32px` etc?
- Usual `className` prop thing so they can make it look nice.
- Some basic themes, so they look nice out of the box.
- Boolean for open in new window.
- Icon families. Allow the consumers to pick the sort of icon look and feel (filled / outline / circle etc)
![image](https://user-images.githubusercontent.com/20924669/119794118-28fb5600-becf-11eb-95f4-a68f264cc96b.png)
Not sure on licenses. I've always recently used https://iconmonstr.com for my projects recently. And their license is very forgiving. https://iconmonstr.com/license/ Just not sure about this bit: 
> Licensee may not sell, redistribute, sublicense, share or otherwise transfer the Work to other people or entities.

---

Also we'll want other ones like Polywork etc which don't exist in sets. So might be that we need to off the shelf sets.

**Comment by andrewbarnesweb** [comment]
@benmatselby is this something you're still interested in progressing? 🙂

**Comment by andrewbarnesweb** [comment]
@benmatselby  Can I ask why? As I'm just drafting some notes about this proposal. Don't see any value in the package? Or is it more the somedevsdo thing that isn't for you right now?

**Comment by andrewbarnesweb** [comment]
This has been moved to a more appropriate place to discuss.
