### ISSUE TITLE
We want nice cards for Twitter, Slack etc

### ISSUE THREAD

**Issue by andrewbarnesweb** [somedevsdo/blog#57]
Utilising Open Graph Image. We want to have nice cards for when stuff is shared on Twitter etc. 

Looks fairly straight forward to do ourselves: https://flaviocopes.com/canvas-node-generate-image/ which I think should be the first option, so we can learn the ins and outs of the tech.

I think we'd probably need to do some sort of build step that generated images for us.

---

Failing the above. We could fork this repo and host our own... https://github.com/vercel/og-image

Essentially we'd have the style and you'd pass in the text to show as a parameter. 

---

It'll give us the ability to do something nice like these:

![image](https://user-images.githubusercontent.com/20924669/119798056-b7250b80-bed2-11eb-8414-5b0538405788.png)

![image](https://user-images.githubusercontent.com/20924669/119798310-ecc9f480-bed2-11eb-9a01-228c85b3a4a5.png)

**Comment by davidn0rman** [comment]
Just spamming some links, don't mind me:

- https://ogp.me/ - The Open Graph protocol website
- https://developers.facebook.com/tools/debug/ - Facebooks sharing debugger
- https://cards-dev.twitter.com/validator - Twitters card validator
 - https://www.freecodecamp.org/news/what-is-open-graph-and-how-can-i-use-it-for-my-website/

**Comment by andrewbarnesweb** [comment]
I've got a local branch that is pretty much doing this now. So _just_ need to get a basic design together and go from there!
