### ISSUE TITLE
Define an author page

### ISSUE THREAD

**Issue by benmatselby** [somedevsdo/blog#7]
Designs here: https://www.figma.com/file/Oc9v5LR4SPwwaQyijhEXnR/Website?node-id=26%3A29

3 sizes, in two colour themes: 
![image](https://user-images.githubusercontent.com/20924669/123748682-6d9e5680-d8ac-11eb-9ff1-70e3e36b44a5.png)

Data should be from a static data store within the repo.

**Comment by benmatselby** [comment]
Some work already done to code up the authors and author specific page, but now needs styling accordingly.

**Comment by andrewbarnesweb** [comment]
Closing as done for now. We just need to mess about with the styles and avatar sizes. We'll need an issue for some accessibility stuff. Like hover/focus states throughout.
