### ISSUE TITLE
Avatars need some sort of solid background colour before the image loads in

### ISSUE THREAD

**Issue by davidn0rman** [somedevsdo/blog#70]
Otherwise, each time we load a page and we fetch an image, we get this fade which looks a bit jank.

![image](https://user-images.githubusercontent.com/20046480/120536158-bbbe5800-c3db-11eb-8406-09e79ebc3c51.png)

Sidenote: Also, can we not cache images? I'd expect once an image is loaded in it'd not need to fade in again, but I'm getting it every time.

**Comment by markgaze** [comment]
This is probably the opacity of the placeholder. If we fixed that then the placeholder _should_ do the job, in theory!

The fade is the transition too, so it'll do it every time, annoyingly. We can probably fix it but as far as I know, they images should be cached, it's just the transition.

**Comment by markgaze** [comment]
Having looked at it, there doesn't seem to be an opacity on the placeholder so must be something else at work here...
