### ISSUE TITLE
Constrain the page to a maximum width

### ISSUE THREAD

**Issue by markgaze** [somedevsdo/blog#75]
If I open the site on an ultrawide monitor, some of the elements are at the very extremes of the page so they're miles apart! We probably want to constrain this to a sensible width.

**Comment by andrewbarnesweb** [comment]
Screenshot for full effect? 😄

**Comment by markgaze** [comment]
Have two! 😂 

![image](https://user-images.githubusercontent.com/16718355/121043628-b599f400-c7ac-11eb-8159-4472e48651fc.png)
![image](https://user-images.githubusercontent.com/16718355/121043680-c0ed1f80-c7ac-11eb-9162-7728d64d2d6c.png)

**Comment by andrewbarnesweb** [comment]
The homepage hero content... I'd expect to see that in line with the main content. 

Not sure what to suggest with logo and theme toggle etc. As they would arguably look a bit weird inset. Do you have any examples of how other sites manage it when they have full width elements? I'm guessing this issue page would be a similar scenario to us? 
![image](https://user-images.githubusercontent.com/20924669/121044660-7d46e580-c7ad-11eb-80de-f5681b63a6b1.png)

**Comment by markgaze** [comment]
Yeah, not a fan of how GitHub handles it but I rarely use it full screen so not a massive problem.

Vercel does this:
![image](https://user-images.githubusercontent.com/16718355/121047104-10801b00-c7ae-11eb-8a82-03483a10a7bb.png)

Svelte Kit:
![image](https://user-images.githubusercontent.com/16718355/121047974-47eec780-c7ae-11eb-93bb-929ad3e3b0c4.png)

So I've got a feeling it's more of a personal preference rather than a standard!

A _certain UI framework site_ we are both incredibly familiar with does it like Vercel... 👀

**Comment by andrewbarnesweb** [comment]
👍🏽 I think it's when there's full width hero images it sort of steers it a bit. But deffo open to trying stuff!

**Comment by andrewbarnesweb** [comment]
This is factored into the new design. Since we don't have hero images anymore, there are defined fixed widths for everything. Including the top bar.

Will close for now, can be reopened if any problems.
