### ISSUE TITLE
Author component is showing wrong theme on dark mode

### ISSUE THREAD

**Issue by andrewbarnesweb** [somedevsdo/blog#83]
I think this is due to a mixture of using CSS variables, and trying to define the theme in the component as well. Potentially we could have the default use CSS variables, and then we can fix a dark version for the homepage header.

![image](https://user-images.githubusercontent.com/20924669/121406142-b91caf00-c955-11eb-973c-fab3094541a5.png)

**Comment by andrewbarnesweb** [comment]
Forgot to resolve! Done.

**Comment by davidn0rman** [comment]
Think I may re-open, as it doesn't appear to be fixed on the posts. :) 

![image](https://user-images.githubusercontent.com/20046480/121787926-0e102d80-cbc1-11eb-843e-d3ffe752af99.png)

**Comment by andrewbarnesweb** [comment]
That's my bad. The Author component needs a `vertical` prop. I'd changed it so that horizontal was the norm. Where's our mate Percy when you need him?!

**Comment by andrewbarnesweb** [comment]
@davidn0rman sorted this 🙂
