### ISSUE TITLE
An entire card should be clickable, not just text

### ISSUE THREAD

**Issue by davidn0rman** [somedevsdo/blog#85]
Currently I can't click the dead space (bottom right) or the image on the card and navigate to the post. I think the entire card should be one big click region, and follows what almost all other blogs I've used do, and will help touch folks view a post.

![image](https://user-images.githubusercontent.com/20046480/121787254-f33bba00-cbbc-11eb-9814-e2357df17771.png)

EG:
https://www.techradar.com/uk/news - Scroll down to cards in a column.
https://www.pcgamer.com/uk/reviews/ - Scroll down to latest updates.
https://blog.google/
https://blog.discord.com/?gi=302e67b7de6d - This does what we do but adds on image clicking. (Which feels nicer than just text)

**Comment by andrewbarnesweb** [comment]
There was an accessibility thing that @benmatselby stumbled into around having links nested in links. So the card link was removed. Because you still might want to click the author?

On Fastly (I think) their cards had a phantom link on the card z-indexed lower than the cards internal links which could be an option 🙂

**Comment by davidn0rman** [comment]
Hmm, maybe! Annoyingly, I thought that Google blog did what we'd likely be after. (Entire card clickable, but other specifics like Author and Category could be their own links) but in checking again, it seems **only** their top posts let you click the category and the image/text for the post, but the rest of them are all just one hit area.

![image](https://user-images.githubusercontent.com/20046480/121790391-eb890f00-cbd6-11eb-9d8f-0bd918762469.png)

Guess we need to weigh up what we'd want. I'm in favour of everything but author/category is a post link. A bit like how a YouTube tile is all clickable except any buttons or the channel name.

**Comment by andrewbarnesweb** [comment]
https://www.fastly.com/blog

**Comment by andrewbarnesweb** [comment]
Closing in favour of the new design. I have designed it so that the entire card is clickable, and the author name isn't. So we won't have the accessibility/semantic issues here anymore.
