### ISSUE TITLE
Theme toggle is wrong if we start in dark mode

### ISSUE THREAD

**Issue by andrewbarnesweb** [somedevsdo/blog#89]
My OS theme is set to dark mode. 

1. When I load the site, it shows the wrong icon (assume OK if I start in light mode). 
2. Clicking the theme toggle then shows the light mode and the correct icon.

Not sure what's going on here. But the video below demos what I'm seeing 🙂 

https://user-images.githubusercontent.com/20924669/122002132-42ded900-cda9-11eb-848c-2f04437e9059.mp4

**Comment by benmatselby** [comment]
I think it is related to this: https://github.com/pacocoursey/next-themes#avoid-hydration-mismatch

So might be worth pulling the theme toggle into it's own component.

**Comment by andrewbarnesweb** [comment]
> I think it is related to this: https://github.com/pacocoursey/next-themes#avoid-hydration-mismatch

This cracked it! Nice one. I've just kept it in layout for now. 🙂
